apiVersion: apps/v1
kind: Deployment
metadata:
  name: ntuc-deployment
  labels:
    name: nginx
    ntcu-k8s: hw3
spec:
  replicas: 1
  selector:
    matchLabels:
      name: nginx-123
  template:
    metadata:
      labels:
        name: nginx-123
    spec:
      containers:
        - name: nginx
          image: nginx:1.7.9
          ports:
            - containerPort: 80
