apiVersion: apps/v1
kind: Deployment
metadata:
  name: informer-exam
spec:
  replicas: 1
  selector:
    matchLabels:
      app : informer-exam
  template:
    metadata:
      labels:
        app : informer-exam
    spec:
      serviceAccountName: dm-incluster
      containers:
        - name: informer-exam
          image: acs107110/incluster:latest
          imagePullPolicy: IfNotPresent
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: dm-incluster
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: dm-incluster-rolebinding
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: dm-role
subjects:
  - kind: ServiceAccount
    name: dm-incluster
    namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: dm-role
  namespace: default
rules:
  - apiGroups:
      - "apps"
      - ""
    resources:
      - deployments
      - services
    verbs:
      - get 
      - create
      - delete
      - list
      - watch
