
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cm-incluster
  namespace: default
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: in-cluster-example
spec:
  replicas: 1
  selector:
    matchLabels:
      app: in-cluster-example
  template:
    metadata:
      labels:
        app: in-cluster-example
    spec:
      serviceAccountName: cm-incluster
      containers:
        - name: in-cluster-example
          image: hw3img
          imagePullPolicy: IfNotPresent
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: cm-role
rules:
  - apiGroups: 
      - ""
      - "apps"
    resources:
      - deployments
      - services
    verbs: 
      - get
      - create
      - delete
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: default
  name: cm-rolebing
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: cm-role
subjects:
  - kind: ServiceAccount
    name: cm-incluster
    namespace: default
